# collection: jomrr.general
# file: .pre-commit-config.yaml
---
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
