# Generated by leg. Collection tests use Podman locally and in CI.
SHELL := /bin/bash
.SHELLFLAGS := -eo pipefail -c
.DEFAULT_GOAL := help
.DELETE_ON_ERROR:
UV ?= uv
PYTHON_VERSION ?= 3.12
ANSIBLE_GROUP ?= ansible-2-20
VENV := .venv
BIN := $(VENV)/bin
VERSION := $(shell awk '$$1 == "version:" { gsub(/["\047]/, "", $$2); print $$2 }' galaxy.yml)
ARTIFACT := dist/jomrr-general-$(VERSION).tar.gz
SOURCE_FILES := $(wildcard $(shell git ls-files --recurse-submodules))
TOOLS := $(BIN)/ansible-test $(BIN)/ansible-galaxy $(BIN)/pre-commit $(BIN)/molecule
PACKAGE_TEST_DIR ?= $(abspath ../../../.collection-tests/jomrr.general)
INSTALLED_MANIFEST := $(PACKAGE_TEST_DIR)/installed/ansible_collections/jomrr/general/MANIFEST.json
PACKAGE_ENV = ANSIBLE_COLLECTIONS_PATH='$(PACKAGE_TEST_DIR)/installed' ANSIBLE_ROLES_PATH='$(PACKAGE_TEST_DIR)/test-roles'
export PATH := $(abspath $(BIN)):$(PATH)
export ANSIBLE_TEST_PREFER_PODMAN := 1
export ANSIBLE_COLLECTIONS_PATH := $(abspath ../../..)

$(BIN)/python:
	$(UV) venv --python $(PYTHON_VERSION) $(VENV)

$(TOOLS) &: pyproject.toml | $(BIN)/python
	$(UV) pip install --python $(BIN)/python --group dev --group $(ANSIBLE_GROUP)
.PHONY: help
help: ## Show targets
	@awk 'BEGIN {FS = ":.*##"} /^[a-z-]+:.*##/ {printf "  %-16s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

.PHONY: sync
sync: $(TOOLS) ## Install tools from pyproject.toml

.PHONY: podman
podman: ## Verify the container engine
	podman version
	podman info

.PHONY: requirements
requirements: $(BIN)/ansible-galaxy ## Install test requirements
	$(BIN)/ansible-galaxy install -r tests/integration/requirements.yml

.PHONY: hooks
hooks: requirements $(TOOLS) ## Run collection and embedded-role hooks
	$(BIN)/pre-commit run --all-files

.PHONY: submodules
submodules: ## Verify initialized submodules match the recorded Gitlinks
	git submodule status --recursive | awk '/^[-+U]/ { print; bad = 1 } END { exit bad }'

.PHONY: sanity
sanity: podman $(BIN)/ansible-test ## Run collection sanity tests
	$(BIN)/ansible-test sanity --docker --python $(PYTHON_VERSION)

.PHONY: units
units: podman $(BIN)/ansible-test ## Run collection unit tests
ifneq ($(wildcard tests/unit),)
	$(BIN)/ansible-test units --docker --python $(PYTHON_VERSION)
else
	@echo 'No tests/unit directory; this collection has no Python unit suite.'
endif

.PHONY: check
check: hooks sanity units ## Run the fast gates

.PHONY: integration
integration: podman $(BIN)/ansible-test ## Run authored module and plugin integration tests
	$(BIN)/ansible-test integration --docker --python $(PYTHON_VERSION)

.PHONY: molecule
molecule: podman requirements $(BIN)/molecule ## Run all configured integration scenarios
	$(BIN)/molecule test --all

.PHONY: build
build: $(ARTIFACT) ## Build the collection tarball

$(ARTIFACT): galaxy.yml meta/runtime.yml README.md $(SOURCE_FILES) | submodules $(BIN)/ansible-galaxy
	$(BIN)/ansible-galaxy collection build --output-path dist/

$(INSTALLED_MANIFEST): $(ARTIFACT) | $(BIN)/ansible-galaxy
	mkdir -p '$(PACKAGE_TEST_DIR)'
	env $(PACKAGE_ENV) $(BIN)/ansible-galaxy collection install --force '$(ARTIFACT)' -p '$(PACKAGE_TEST_DIR)/installed'

.PHONY: package-requirements
package-requirements: $(INSTALLED_MANIFEST) ## Install isolated integration dependencies
	env $(PACKAGE_ENV) $(BIN)/ansible-galaxy collection install -r tests/integration/requirements.yml -p '$(PACKAGE_TEST_DIR)/installed'
	env $(PACKAGE_ENV) $(BIN)/ansible-galaxy role install -r tests/integration/requirements.yml -p '$(PACKAGE_TEST_DIR)/test-roles'

.PHONY: package-test
package-test: package-requirements podman $(BIN)/molecule ## Test the installed package outside this checkout
	tar -tzf '$(ARTIFACT)' | awk '/(^|\/)(\.git|\.gitmodules|\.venv)(\/|$$)/ { print; bad = 1 } END { exit bad }'
ifneq ($(wildcard tests/integration/package.yml),)
	rm -rf '$(PACKAGE_TEST_DIR)/integration'
	mkdir -p '$(PACKAGE_TEST_DIR)/integration'
	cp -R tests/integration/. '$(PACKAGE_TEST_DIR)/integration/'
	cd '$(PACKAGE_TEST_DIR)' && env $(PACKAGE_ENV) $(abspath $(BIN))/ansible-playbook -i localhost, -c local -e 'ansible_python_interpreter=$(abspath $(BIN))/python' integration/package.yml
endif

.PHONY: clean
clean: ## Remove local build output
	rm -rf dist docs/rst docs/build tests/output .mypy_cache .ruff_cache .pytest_cache
