---
name: dev
"on":
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      full: false
