---
name: dev
"on":
  push:
    branches: ["dev"]
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - "CHANGELOG.rst"
      - "Makefile"
      - "pyproject.toml"
      - "architecture/**"
  pull_request:
    branches: ["dev"]
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - "CHANGELOG.rst"
      - "Makefile"
      - "pyproject.toml"
      - "architecture/**"
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test.yml
